export default {
  // Common / Shared
  common: {
    required_field: 'This field is required',
    login: 'Login',
    logout: 'Logout',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    update: 'Update',
    cancel: 'Cancel',
    yes: 'Yes',
    no: 'No',
    save: 'Save',
    close: 'Close',
    copy: 'Copy',
    search: 'Search',
    reload: 'Reload',
    execute: 'Execute',
    register: 'Register',
    new_registration: 'New Registration',
    new_creation: 'Create New',
    new_execution: 'New Run',
    batch_delete: 'Bulk Delete',
    batch_add: 'Bulk Add',
    copy_execution: 'Copy & Run',
    run_preprocessing: 'Run Preprocessing',
    detailed_search: 'Advanced Search',
    searching: '(Searching...)',
    version_info: 'Version Info',
    version_label: 'Version:',
    user_settings: 'User Settings',
    data_download: 'Data Download',
    flat: 'Flat',
    with_header: 'Yes',
    without_header: 'No',
    group: 'Group',
    system: 'System',
    local: 'Local',
    default_label: '(Default)',
    public_access: 'Public',
    allow_logged_in: 'Allow Logged-in Users',
    allowed: 'Allow',
    forbidden: 'Forbid',
    executable: 'Execute',
    not_executable: 'Do not execute',
    editable: 'Yes',
    not_editable: 'No',
    history: 'History',
    script: 'Script',
    tag_change: 'Change Tags',
    sync_start: 'Start Sync',
    start_date: 'Start Date',
    end_date: 'End Date',
    count: 'Count',
    count_suffix: 'items',
    download_history: 'Download History',
    delete_history: 'Delete History',
    header_label: 'Header',
    saved_history: 'Saved History',
    confirm: 'Confirm',
    cancelled: 'Cancelled',
    back: 'Back',
    view: 'View',
    get: 'Get',
    open: 'Open',
    start: 'Start',
    stop: 'Stop',
    rerun: 'Rerun',
    restart: 'Restart',
    test_notification: 'Test Notification',
    show_image: 'Show Image',
    new_tag: '+ New Tag',
    unlimited: 'Unlimited',
    no_expiration: 'No expiration',
    default: 'Default',
    contains: 'contains',
    not_contains: 'not contains',
    equals: 'equals',
    gte: 'greater than or equal',
    lte: 'less than or equal',
    gt: 'greater than',
    lt: 'less than',
    gt_detail: 'exceeds',
    lt_detail: 'less than',
    local_copy: 'Local Copy',
    symbolic_link: 'Symbolic Link',
    compress: 'Compress',
    no_compress: 'Do not compress',
    normal_stop: 'Normal Stop',
    abnormal_stop: 'Abnormal Stop',
    inference_execution: 'Run Inference',
  },

  // Labels
  labels: {
    id: 'ID',
    name: 'Name',
    memo: 'Memo',
    tag: 'Tag',
    tags: 'Tags',
    status: 'Status',
    type: 'Type',
    created_at: 'Created At',
    created_at_short: 'Created At',
    started_at: 'Started At',
    execution_time_at: 'Executed At',
    completed_at: 'Completed At',
    created_by: 'Created By',
    started_by: 'Executed By',
    author: 'Author',
    data_name: 'Data Name',
    dataset_name: 'Dataset Name',
    training_name: 'Training Name',
    preprocessing_name: 'Preprocessing Name',
    inference_name: 'Inference Name',
    notebook_name: 'Notebook Name',
    entry_point: 'Entry Point',
    dataset: 'Dataset',
    mounted_training: 'Mounted Training',
    mounted_inference: 'Mounted Inference',
    parent_data_name: 'Source Data Name',
    data_file: 'Data Files',
    placement_type: 'Placement Type',
    edit_permission: 'Editable',
    data: 'Data',
    registry_name: 'Registry Name',
    registry_path: 'Registry Path',
    gitlab_project: 'GitLab Project Name',
    host_name: 'Host Name',
    port: 'Port',
    project_name: 'Project Name',
    host_port: 'Host:Port',
    repository_name: 'Repository Name',
    repository_url: 'Repository URL',
    repository: 'Repository',
    node_name: 'Node Name',
    node: 'Node',
    tenant: 'Tenant',
    tenant_name: 'Tenant Name',
    display_name: 'Display Name',
    partition: 'Partition',
    access_level: 'Access Level',
    access_denied: 'Access Denied',
    access_allowed: 'Access Allowed',
    access_permission_role: 'Access Permission Role',
    user_name: 'User Name',
    user_display_name: 'User Display Name',
    auth_type: 'Auth Type',
    password: 'Password',
    password_reenter: 'Password (Re-enter)',
    password_change_only: 'Password (Enter only to change)',
    system_role: 'System Role',
    role: 'Role',
    role_name: 'Role Name',
    sort_order: 'Sort Order',
    display_order: 'Display Order',
    user_group_name: 'User Group Name',
    tenant_role: 'Tenant Role',
    storage_name: 'Storage Name',
    access_key: 'Access Key',
    secret_key: 'Secret Key',
    nfs_server: 'NFS Server',
    nfs_export_point: 'NFS Export Point',
    menu_name: 'Menu Name',
    description: 'Description',
    container: 'Container',
    container_name: 'Container Name',
    container_image: 'Container Image',
    memory: 'Memory',
    memory_gb: 'Memory (GB)',
    user: 'User',
    input_data_id: 'Input Data ID',
    input_data_name: 'Input Data Name',
    dn_direct_users_only: 'Allow only users directly under DN',
    notebook_unlimited_exec: 'Notebook Unlimited Execution',
    ldap_user_id: 'LDAP User ID',
    ldap_password: 'LDAP Password',
    expiration: 'Expiration',
    days: 'days',
    git_repository: 'Git Repository',
    environment_variable: 'Environment Variables',
    resource: 'Resource',
    cpu: 'CPU',
    gpu: 'GPU',
    option: 'Option',
    zip_expand: 'Unzip',
    output_file: 'Output Files',
    output_data_id: 'Output Data ID',
    attached_file: 'Attached Files',
    result_file: 'Result Files',
    execution_time: 'Execution Time',
    waiting_time: 'Waiting Time',
    favorite: 'Favorite',
    image_name: 'Image Name',
    image: 'Image',
    token: 'Token',
    default_tenant: 'Default Tenant',
    webhook_url: 'Webhook URL',
    expose_port: 'Exposed Ports',
    expose_port_tcp: 'Exposed Ports (TCP)',
    container_output_file: 'Container Output Files',
    bulk_download_command: 'Bulk Download Command',
    result_zip: 'Result Zip Compression',
    dataset_creation_method: 'Dataset Creation Method',
    model: 'Model',
    startup_command: 'Startup Command',
    startup_period: 'Startup Period',
    startup_period_h: 'Startup Period (h)',
    startup_period_setting: 'Startup Period Setting',
    jupyter_version: 'JupyterLab Version to Install',
    operation: 'Operation',
    log: 'Log',
    log_file: 'Log File',
    preprocessing_log: 'Preprocessing Log',
    preprocessing_history_id: 'Preprocessing History ID',
    data_id: 'Data ID',
    storage_path: 'Storage Path',
    storage_info: 'Storage Info',
    docker_registry_info: 'Docker Registry Info',
    registry: 'Registry',
    git_info: 'Git Info',
    git_server: 'Git Server',
    user_group_info: 'User Group Info',
    branch: 'Branch',
    commit_id: 'Commit ID',
    committer: 'Committer',
    commit_date: 'Commit Date',
    comment: 'Comment',
    file_name: 'File Name',
    size: 'Size',
    updated_at: 'Updated At',
    variable_name: 'Variable Name',
    value: 'Value',
    port_number: 'Port Number',
    parent_training_name: 'Parent Training Name',
    mounted_training_id: 'Mounted Training ID',
    mounted_training_name: 'Mounted Training Name',
    mounted_inference_id: 'Mounted Inference ID',
    mounted_inference_name: 'Mounted Inference Name',
    output_value: 'Output Value',
    notification_url: 'Notification URL',
    mention: 'Mention',
    current_password: 'Current Password (Enter only to change)',
    new_password: 'New Password (Enter only to change)',
    reenter: '(Re-enter)',
    selected_git_repo: 'Selected Git Repository',
    selected_registry: 'Selected Registry',
    selected_tenant: 'Selected Tenant',
    user_name_repo: 'User Name/Repository',
    remaining_time: 'Remaining Time',
    additional_training_results: 'Additional Training Results',
    container_access: 'Container Access',
    request_resource: 'Requested Resources',
    days_until_expiry: 'Days until expiry',
    registration_name: 'Registration Name',
    quota_info: 'Quota Info',
    default_tenant_label: 'Default Tenant',
  },

  // Page Titles
  titles: {
    data_management: 'Data Management',
    dataset_management: 'Dataset Management',
    training_management: 'Training Management',
    inference_management: 'Inference Management',
    notebook_management: 'Notebook Management',
    preprocessing_management: 'Preprocessing Management',
    preprocessing_history: 'Preprocessing History',
    registry_management: 'Registry Management',
    git_management: 'Git Management',
    storage_management: 'Storage Management',
    node_management: 'Node Management',
    user_management: 'User Management',
    user_group_management: 'User Group Management',
    role_management: 'Role Management',
    quota_management: 'Quota Management',
    menu_access_management: 'Menu Access Management',
    resource_usage: 'Resource Usage',
    tenant_management: 'Tenant Management',
    data_registration: 'Data Registration',
    data_edit: 'Data Edit',
    dataset_creation: 'Create Dataset',
    dataset_edit: 'Edit Dataset',
    training_creation: 'Create Training',
    training_edit: 'Edit Training',
    training_history: 'Training History',
    training_execution: 'Run Training',
    inference_creation: 'Create Inference',
    inference_edit: 'Edit Inference',
    inference_history: 'Inference History',
    inference_execution: 'Run Inference',
    notebook_creation: 'Create Notebook',
    notebook_edit: 'Edit Notebook',
    notebook_history: 'Notebook History',
    notebook_launch: 'Launch Notebook',
    preprocessing_creation: 'Create Preprocessing',
    preprocessing_edit: 'Edit Preprocessing',
    preprocessing_history_edit: 'Edit Preprocessing History',
    preprocessing_history_detail: 'Preprocessing History Details',
    registry_registration: 'Docker Registry Registration',
    registry_edit: 'Docker Registry Edit',
    git_registration: 'Git Registration',
    git_edit: 'Git Edit',
    storage_registration: 'Storage Registration',
    storage_edit: 'Storage Edit',
    storage_info: 'Storage Info',
    registry_info: 'Registry Info',
    node_registration: 'Node Registration',
    node_edit: 'Node Edit',
    user_creation: 'Create User',
    user_edit: 'Edit User',
    user_group_registration: 'User Group Registration',
    user_group_edit: 'User Group Edit',
    role_creation: 'Create Role',
    role_edit: 'Edit Role',
    tenant_creation: 'Create Tenant',
    tenant_edit: 'Edit Tenant',
    tenant_info: 'Tenant Info',
    container_resource: 'Container Resources',
    job_execution_history: 'Job Execution History',
    ldap_sync: 'LDAP Server Sync',
    dashboard: 'Dashboard',
    tenant_resource_management: 'Tenant Resource Management',
    tenant_setting: 'Connected Tenant Settings',
    tenant_user_management: 'Tenant User Management',
    tenant_user_edit: 'Tenant User Edit',
    user_info_settings: 'User Settings',
    error: 'Error',
    file_list: 'File List',
    container_info: 'Container Info',
    run_preprocessing: 'Run Preprocessing',
    container_execution_result: 'Container Execution Result',
    status_detail_log: 'Status Detail Log',
    commit_detail: 'Commit Details',
    mounted_training_detail: 'Mounted Training Details',
    mounted_inference_detail: 'Mounted Inference Details',
    dataset_detail: 'Dataset Details',
    training_detail: 'Training Details',
    inference_detail: 'Inference Details',
    preprocessing_detail: 'Preprocessing Details',
    node_info: 'Node Info',
    save_search: 'Save Search Conditions',
    add_training_results: 'Additional Training Results to Display',
  },

  // Messages
  messages: {
    process_success: 'Successfully processed',
    please_login: 'Please log in',
    no_valid_auth: 'No valid authentication information',
    auth_error: 'Authentication error: Please log in.',
    select_one_file: 'Please select at least one file',
    max_files: 'Maximum number of files per data is {max}',
    data_registration_failed: 'Data registration failed',
    enter_same_password: 'Please enter the same password',
    role_not_selected: 'Some tenants have no role selected',
    sort_order_description:
      'Sort order. Smaller values appear first. Uniqueness is not required.',
    tenant_delete_confirm:
      'Deleting the tenant will result in loss of data associated with it. Please enter the tenant name to continue.',
    user_delete_confirm:
      'Deleting the user will result in loss of user info from associated tenants. Please enter the user name to continue.',
    user_group_change_confirm:
      'Users belonging to unlinked user groups will no longer be able to join this tenant. Save changes?',
    ldap_sync_description:
      'Queries the LDAP server to update tenant membership and permission info for all users.',
    ldap_sync_time_warning: 'Synchronization may take some time.',
    ldap_sync_confirm:
      'Start synchronization? If there are many users, it may take some time to complete.',
    history_not_found: 'No history found.',
    auth_type_unknown: 'Auth Type: Unknown',
    user_group_tenants: 'Tenants joined via user groups',
    user_group_tenant_roles: 'Tenant roles via user groups',
    delete_container_history_all: 'Delete all container resource history?',
    delete_container_history_until: ' container resource history?',
    delete_job_history_all: 'Delete all job execution history?',
    delete_job_history_until: ' job execution history?',
    move_to: 'Move selection to {name}',
    remove_selection: 'Remove selection',
    page_of: 'page',
    tenant_custom: 'Tenant (Custom)',
    tenant_common: 'Tenant (Common)',
    tenant_custom_with_name: 'Tenant (Custom) / ',
    input_mismatch: 'Input does not match',
    delete_confirm: 'Are you sure you want to delete?',
    delete_confirm_output:
      'Are you sure you want to delete? (Processing may take time if there are many output data)',
    stop_confirm: 'Are you sure you want to stop?',
    job_stop: 'Stop Job',
    job_stop_confirm: 'Are you sure you want to stop this job?',
    no_log_file: 'No log file available.',
    check_after_preprocessing: 'Check history after execution',
    preprocessing_executed: 'Preprocessing executed for ID:{dataId}',
    preprocessing_failed: 'Preprocessing failed',
    open_notebook: 'Open Notebook',
    file_list: 'File List',
    log_file_view: 'View Log File',
    shell_launch: 'Launch Shell',
    tensorboard_show: 'Show TensorBoard',
    checking_status: 'Checking status...',
    waiting_resource: 'Waiting for available resources...',
    starting: 'Starting...',
    stopping: 'Stopping...',
    start_failed: 'Start failed',
    git_not_selected:
      'No Git repository is selected. Please contact the system administrator.',
    registry_not_selected:
      'No Registry is selected. Please contact the system administrator.',
    token_display_warning:
      'The token is only displayed at issuance. Make sure to save it.',
    token_reissue_warning:
      'Reissuing a token will invalidate the previous token.',
    token_issue: 'Issue Token',
    token_reissue: 'Reissue',
    new_issue: 'Issue New',
    days_input_range: 'Please enter a number between 1 and 3650.',
    error_page_title: 'An invalid operation was performed.',
    error_page_not_found: 'The page "{url}" was not found.',
    error_code: 'Code: {status}',
    error_message: 'Message: {message}',
    error_resolution: 'Solutions',
    error_retry: '- Please try the operation again',
    error_manual: '- Check the manual',
    error_server: 'An error has been recorded on the server.',
    error_patience: 'We are working hard to resolve it. Please wait a moment.',
    data_too_large:
      'The data is too large to display. Please download it to check.',
    dataset_path_info:
      'Reference: Data paths and names for selected dataset [{name}]',
    no_available_nodes: 'No available nodes.',
    contact_admin: 'Please contact the system administrator.',
    resource_changed_from_original: 'From the original requested resources, ',
    resource_value_changed: ' values have been changed.',
    node_no_resource:
      'The node does not have enough {resources} resources for the request.',
    no_executable_node: 'No node has enough resources to execute the request.',
    latest_commit: 'This is the latest commit.',
    commits_before: 'This is {index} commits before the latest.',
    commits_older: 'This is more than {count} commits before the latest.',
    committer_label: 'Committer:',
    comment_none: 'Comment: none',
    comment_label: 'Comment: ',
    training_delete_confirm:
      'Delete {count} training histories? (Processing may take time if there are many output data)',
    training_deleted:
      'Training histories deleted. (Success: {success}, Failed: {fail})',
    inference_delete_confirm:
      'Delete {count} inference histories? (Processing may take time if there are many output data)',
    inference_deleted:
      'Inference histories deleted. (Success: {success}, Failed: {fail})',
    only_completed_training:
      'Inference can only be run on training with Completed or UserCanceled status.',
    save_search_condition: 'Save search conditions',
    min_chars: 'Please enter at least {count} characters',
    shell_copy_paste:
      'Copy: Ctrl+Insert, Paste: Shift+Insert (In Google Chrome, Ctrl+Shift+V also works for pasting)',
    notebook_default_version: 'Default: 3.4.2',
    notebook_version_description:
      'Default: 3.4.2 (Will be skipped if JupyterLab is already installed in the container image)',
    tenant_user_remove_confirm:
      'Excluding the user will prevent them from accessing the current tenant. Please enter the user name to continue.',
  },

  // Cluster resource / Node view
  cluster: {
    by_node: 'By Node',
    by_tenant: 'By Tenant',
    container_list: 'Container List',
  },

  // LDAP
  ldap: {
    ldap_sync: 'LDAP Sync',
  },

  // Pagination
  pagination: {
    total: 'Total {total} items',
  },

  // Dashboard
  dashboard: {
    running_jobs: 'Running Jobs',
    favorite_jobs: 'Favorite Jobs',
    no_running_jobs: 'No running jobs',
    no_favorites: 'No favorites',
  },

  // Search configs
  search: {
    name: 'Name',
    status: 'Status',
  },

  // Steps
  steps: {
    training_name_dataset: 'Training Name & Dataset',
    inference_name_dataset: 'Inference Name & Dataset',
    container_model: 'Container & Model',
    resource: 'Resource',
    option: 'Option',
    notebook_name: 'Notebook Name',
    resource_period: 'Resource & Startup Period',
    optional: 'Optional',
  },
}
