export default {
  // Common / Shared
  common: {
    required_field: 'Este campo es obligatorio',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    create: 'Crear',
    edit: 'Editar',
    delete: 'Eliminar',
    update: 'Actualizar',
    cancel: 'Cancelar',
    yes: 'Sí',
    no: 'No',
    save: 'Guardar',
    close: 'Cerrar',
    copy: 'Copiar',
    search: 'Buscar',
    reload: 'Recargar',
    execute: 'Ejecutar',
    register: 'Registrar',
    new_registration: 'Nuevo registro',
    new_creation: 'Crear nuevo',
    new_execution: 'Nueva ejecución',
    batch_delete: 'Eliminación masiva',
    batch_add: 'Adición masiva',
    copy_execution: 'Copiar y ejecutar',
    run_preprocessing: 'Ejecutar preprocesamiento',
    detailed_search: 'Búsqueda avanzada',
    searching: '(Buscando...)',
    version_info: 'Información de versión',
    version_label: 'Versión:',
    user_settings: 'Configuración de usuario',
    data_download: 'Descarga de datos',
    flat: 'Plano',
    with_header: 'Sí',
    without_header: 'No',
    group: 'Grupo',
    system: 'Sistema',
    local: 'Local',
    default_label: '(Predeterminado)',
    public_access: 'Público',
    allow_logged_in: 'Permitir usuarios autenticados',
    allowed: 'Permitir',
    forbidden: 'Prohibir',
    executable: 'Ejecutar',
    not_executable: 'No ejecutar',
    editable: 'Sí',
    not_editable: 'No',
    history: 'Historial',
    script: 'Script',
    tag_change: 'Cambiar etiquetas',
    sync_start: 'Iniciar sincronización',
    start_date: 'Fecha de inicio',
    end_date: 'Fecha de fin',
    count: 'Cantidad',
    count_suffix: 'elementos',
    download_history: 'Descargar historial',
    delete_history: 'Eliminar historial',
    header_label: 'Encabezado',
    saved_history: 'Historial guardado',
    confirm: 'Confirmar',
    cancelled: 'Cancelado',
    back: 'Volver',
    view: 'Ver',
    get: 'Obtener',
    open: 'Abrir',
    start: 'Iniciar',
    stop: 'Detener',
    rerun: 'Reejecutar',
    restart: 'Reiniciar',
    test_notification: 'Notificación de prueba',
    show_image: 'Mostrar imagen',
    new_tag: '+ Nueva etiqueta',
    unlimited: 'Ilimitado',
    no_expiration: 'Sin vencimiento',
    default: 'Predeterminado',
    contains: 'contiene',
    not_contains: 'no contiene',
    equals: 'igual a',
    gte: 'mayor o igual',
    lte: 'menor o igual',
    gt: 'mayor que',
    lt: 'menor que',
    gt_detail: 'excede',
    lt_detail: 'menor que',
    local_copy: 'Copia local',
    symbolic_link: 'Enlace simbólico',
    compress: 'Comprimir',
    no_compress: 'No comprimir',
    normal_stop: 'Detención normal',
    abnormal_stop: 'Detención anormal',
    inference_execution: 'Ejecutar inferencia',
  },

  // Labels
  labels: {
    id: 'ID',
    name: 'Nombre',
    memo: 'Nota',
    tag: 'Etiqueta',
    tags: 'Etiquetas',
    status: 'Estado',
    type: 'Tipo',
    created_at: 'Fecha de registro',
    created_at_short: 'Fecha de creación',
    started_at: 'Fecha de inicio',
    execution_time_at: 'Fecha de ejecución',
    completed_at: 'Fecha de finalización',
    created_by: 'Registrado por',
    started_by: 'Ejecutado por',
    author: 'Autor',
    data_name: 'Nombre de datos',
    dataset_name: 'Nombre del dataset',
    training_name: 'Nombre del entrenamiento',
    preprocessing_name: 'Nombre del preprocesamiento',
    inference_name: 'Nombre de la inferencia',
    notebook_name: 'Nombre del notebook',
    entry_point: 'Comando de ejecución',
    dataset: 'Dataset',
    mounted_training: 'Entrenamiento montado',
    mounted_inference: 'Inferencia montada',
    parent_data_name: 'Nombre de datos original',
    data_file: 'Archivos de datos',
    placement_type: 'Tipo de ubicación',
    edit_permission: 'Editable',
    data: 'Datos',
    registry_name: 'Nombre del registro',
    registry_path: 'Ruta del registro',
    gitlab_project: 'Nombre del proyecto GitLab',
    host_name: 'Nombre del host',
    port: 'Puerto',
    project_name: 'Nombre del proyecto',
    host_port: 'Host:Puerto',
    repository_name: 'Nombre del repositorio',
    repository_url: 'URL del repositorio',
    repository: 'Repositorio',
    node_name: 'Nombre del nodo',
    node: 'Nodo',
    tenant: 'Inquilino',
    tenant_name: 'Nombre del inquilino',
    display_name: 'Nombre para mostrar',
    partition: 'Partición',
    access_level: 'Nivel de acceso',
    access_denied: 'Acceso denegado',
    access_allowed: 'Acceso permitido',
    access_permission_role: 'Rol de permiso de acceso',
    user_name: 'Nombre de usuario',
    user_display_name: 'Nombre visible del usuario',
    auth_type: 'Tipo de autenticación',
    password: 'Contraseña',
    password_reenter: 'Contraseña (Reingresar)',
    password_change_only: 'Contraseña (Ingrese solo para cambiar)',
    system_role: 'Rol del sistema',
    role: 'Rol',
    role_name: 'Nombre del rol',
    sort_order: 'Orden de clasificación',
    display_order: 'Orden de visualización',
    user_group_name: 'Nombre del grupo de usuarios',
    tenant_role: 'Rol de inquilino',
    storage_name: 'Nombre del almacenamiento',
    access_key: 'Clave de acceso',
    secret_key: 'Clave secreta',
    nfs_server: 'Servidor NFS',
    nfs_export_point: 'Punto de exportación NFS',
    menu_name: 'Nombre del menú',
    description: 'Descripción',
    container: 'Contenedor',
    container_name: 'Nombre del contenedor',
    container_image: 'Imagen de contenedor',
    memory: 'Memoria',
    memory_gb: 'Memoria (GB)',
    user: 'Usuario',
    input_data_id: 'ID de datos de entrada',
    input_data_name: 'Nombre de datos de entrada',
    dn_direct_users_only: 'Permitir solo usuarios directamente bajo DN',
    notebook_unlimited_exec: 'Ejecución ilimitada de notebook',
    ldap_user_id: 'ID de usuario LDAP',
    ldap_password: 'Contraseña LDAP',
    expiration: 'Fecha de vencimiento',
    days: 'días',
    git_repository: 'Repositorio Git',
    environment_variable: 'Variables de entorno',
    resource: 'Recurso',
    cpu: 'CPU',
    gpu: 'GPU',
    option: 'Opción',
    zip_expand: 'Descomprimir zip',
    output_file: 'Archivos de salida',
    output_data_id: 'ID de datos de salida',
    attached_file: 'Archivos adjuntos',
    result_file: 'Archivos de resultados',
    execution_time: 'Tiempo de ejecución',
    waiting_time: 'Tiempo de espera',
    favorite: 'Favorito',
    image_name: 'Nombre de imagen',
    image: 'Imagen',
    token: 'Token',
    default_tenant: 'Inquilino predeterminado',
    webhook_url: 'URL del Webhook',
    expose_port: 'Puertos expuestos',
    expose_port_tcp: 'Puertos expuestos (TCP)',
    container_output_file: 'Archivos de salida del contenedor',
    bulk_download_command: 'Comando de descarga masiva',
    result_zip: 'Compresión Zip de resultados',
    dataset_creation_method: 'Método de creación del dataset',
    model: 'Modelo',
    startup_command: 'Comando de inicio',
    startup_period: 'Período de inicio',
    startup_period_h: 'Período de inicio (h)',
    startup_period_setting: 'Configuración del período de inicio',
    jupyter_version: 'Versión de JupyterLab a instalar',
    operation: 'Operación',
    log: 'Registro',
    log_file: 'Archivo de registro',
    preprocessing_log: 'Registro de preprocesamiento',
    preprocessing_history_id: 'ID de historial de preprocesamiento',
    data_id: 'ID de datos',
    storage_path: 'Ruta de almacenamiento',
    storage_info: 'Información de almacenamiento',
    docker_registry_info: 'Información del Docker Registry',
    registry: 'Registro',
    git_info: 'Información de Git',
    git_server: 'Servidor Git',
    user_group_info: 'Información del grupo de usuarios',
    branch: 'Rama',
    commit_id: 'ID de commit',
    committer: 'Autor del commit',
    commit_date: 'Fecha del commit',
    comment: 'Comentario',
    file_name: 'Nombre del archivo',
    size: 'Tamaño',
    updated_at: 'Fecha de actualización',
    variable_name: 'Nombre de variable',
    value: 'Valor',
    port_number: 'Número de puerto',
    parent_training_name: 'Nombre del entrenamiento padre',
    mounted_training_id: 'ID de entrenamiento montado',
    mounted_training_name: 'Nombre de entrenamiento montado',
    mounted_inference_id: 'ID de inferencia montada',
    mounted_inference_name: 'Nombre de inferencia montada',
    output_value: 'Valor de salida',
    notification_url: 'URL de notificación',
    mention: 'Mención',
    current_password: 'Contraseña actual (Ingrese solo para cambiar)',
    new_password: 'Nueva contraseña (Ingrese solo para cambiar)',
    reenter: '(Reingresar)',
    selected_git_repo: 'Repositorio Git seleccionado',
    selected_registry: 'Registry seleccionado',
    selected_tenant: 'Inquilino seleccionado',
    user_name_repo: 'Nombre de usuario/Repositorio',
    remaining_time: 'Tiempo restante',
    additional_training_results: 'Resultados de entrenamiento adicionales',
    container_access: 'Acceso al contenedor',
    request_resource: 'Recursos solicitados',
    days_until_expiry: 'Días hasta el vencimiento',
    registration_name: 'Nombre de registro',
    quota_info: 'Información de cuota',
    default_tenant_label: 'Inquilino predeterminado',
  },

  // Page Titles
  titles: {
    data_management: 'Gestión de datos',
    dataset_management: 'Gestión de datasets',
    training_management: 'Gestión de entrenamiento',
    inference_management: 'Gestión de inferencia',
    notebook_management: 'Gestión de notebooks',
    preprocessing_management: 'Gestión de preprocesamiento',
    preprocessing_history: 'Historial de preprocesamiento',
    registry_management: 'Gestión de registros',
    git_management: 'Gestión de Git',
    storage_management: 'Gestión de almacenamiento',
    node_management: 'Gestión de nodos',
    user_management: 'Gestión de usuarios',
    user_group_management: 'Gestión de grupos de usuarios',
    role_management: 'Gestión de roles',
    quota_management: 'Gestión de cuotas',
    menu_access_management: 'Gestión de acceso al menú',
    resource_usage: 'Uso de recursos',
    tenant_management: 'Gestión de inquilinos',
    data_registration: 'Registro de datos',
    data_edit: 'Edición de datos',
    dataset_creation: 'Crear dataset',
    dataset_edit: 'Editar dataset',
    training_creation: 'Crear entrenamiento',
    training_edit: 'Editar entrenamiento',
    training_history: 'Historial de entrenamiento',
    training_execution: 'Ejecutar entrenamiento',
    inference_creation: 'Crear inferencia',
    inference_edit: 'Editar inferencia',
    inference_history: 'Historial de inferencia',
    inference_execution: 'Ejecutar inferencia',
    notebook_creation: 'Crear notebook',
    notebook_edit: 'Editar notebook',
    notebook_history: 'Historial de notebook',
    notebook_launch: 'Iniciar notebook',
    preprocessing_creation: 'Crear preprocesamiento',
    preprocessing_edit: 'Editar preprocesamiento',
    preprocessing_history_edit: 'Editar historial de preprocesamiento',
    preprocessing_history_detail: 'Detalles del historial de preprocesamiento',
    registry_registration: 'Registro de Docker Registry',
    registry_edit: 'Edición de Docker Registry',
    git_registration: 'Registro de Git',
    git_edit: 'Edición de Git',
    storage_registration: 'Registro de almacenamiento',
    storage_edit: 'Edición de almacenamiento',
    storage_info: 'Información de almacenamiento',
    registry_info: 'Información del registro',
    node_registration: 'Registro de nodo',
    node_edit: 'Edición de nodo',
    user_creation: 'Crear usuario',
    user_edit: 'Editar usuario',
    user_group_registration: 'Registro de grupo de usuarios',
    user_group_edit: 'Edición de grupo de usuarios',
    role_creation: 'Crear rol',
    role_edit: 'Editar rol',
    tenant_creation: 'Crear inquilino',
    tenant_edit: 'Editar inquilino',
    tenant_info: 'Información del inquilino',
    container_resource: 'Recursos de contenedor',
    job_execution_history: 'Historial de ejecución de trabajos',
    ldap_sync: 'Sincronización de servidor LDAP',
    dashboard: 'Panel de control',
    tenant_resource_management: 'Gestión de recursos del inquilino',
    tenant_setting: 'Configuración de inquilino conectado',
    tenant_user_management: 'Gestión de usuarios del inquilino',
    tenant_user_edit: 'Edición de usuario del inquilino',
    user_info_settings: 'Configuración de usuario',
    error: 'Error',
    file_list: 'Lista de archivos',
    container_info: 'Información del contenedor',
    run_preprocessing: 'Ejecutar preprocesamiento',
    container_execution_result: 'Resultado de ejecución del contenedor',
    status_detail_log: 'Registro detallado de estado',
    commit_detail: 'Detalles del commit',
    mounted_training_detail: 'Detalles del entrenamiento montado',
    mounted_inference_detail: 'Detalles de la inferencia montada',
    dataset_detail: 'Detalles del dataset',
    training_detail: 'Detalles del entrenamiento',
    inference_detail: 'Detalles de la inferencia',
    preprocessing_detail: 'Detalles del preprocesamiento',
    node_info: 'Información del nodo',
    save_search: 'Guardar condiciones de búsqueda',
    add_training_results: 'Resultados de entrenamiento adicionales a mostrar',
  },

  // Messages
  messages: {
    process_success: 'Procesado exitosamente',
    please_login: 'Inicie sesión',
    no_valid_auth: 'No hay información de autenticación válida',
    auth_error: 'Error de autenticación: Por favor, inicie sesión.',
    select_one_file: 'Seleccione al menos un archivo',
    max_files: 'El número máximo de archivos por dato es {max}',
    data_registration_failed: 'Error en el registro de datos',
    enter_same_password: 'Ingrese la misma contraseña',
    role_not_selected: 'Algunos inquilinos no tienen un rol seleccionado',
    sort_order_description:
      'Orden de clasificación. Los valores más pequeños aparecen primero. No se requiere unicidad.',
    tenant_delete_confirm:
      'Eliminar el inquilino resultará en la pérdida de datos asociados. Ingrese el nombre del inquilino para continuar.',
    user_delete_confirm:
      'Eliminar el usuario resultará en la pérdida de información del usuario de los inquilinos asociados. Ingrese el nombre de usuario para continuar.',
    user_group_change_confirm:
      'Los usuarios pertenecientes a grupos de usuarios desvinculados ya no podrán unirse a este inquilino. ¿Guardar cambios?',
    ldap_sync_description:
      'Consulta el servidor LDAP para actualizar la membresía de inquilinos y la información de permisos de todos los usuarios.',
    ldap_sync_time_warning: 'La sincronización puede tardar un tiempo.',
    ldap_sync_confirm:
      '¿Iniciar sincronización? Si hay muchos usuarios, puede tardar un tiempo en completarse.',
    history_not_found: 'No se encontró historial.',
    auth_type_unknown: 'Tipo de autenticación: Desconocido',
    user_group_tenants: 'Inquilinos unidos a través de grupos de usuarios',
    user_group_tenant_roles:
      'Roles de inquilino a través de grupos de usuarios',
    delete_container_history_all:
      '¿Eliminar todo el historial de recursos de contenedor?',
    delete_container_history_until: ' historial de recursos de contenedor?',
    delete_job_history_all:
      '¿Eliminar todo el historial de ejecución de trabajos?',
    delete_job_history_until: ' historial de ejecución de trabajos?',
    move_to: 'Mover selección a {name}',
    remove_selection: 'Eliminar selección',
    page_of: 'página',
    tenant_custom: 'Inquilino (Personalizado)',
    tenant_common: 'Inquilino (Común)',
    tenant_custom_with_name: 'Inquilino (Personalizado) / ',
    input_mismatch: 'La entrada no coincide',
    delete_confirm: '¿Está seguro de que desea eliminar?',
    delete_confirm_output:
      '¿Está seguro de que desea eliminar? (El procesamiento puede tardar si hay muchos datos de salida)',
    stop_confirm: '¿Está seguro de que desea detener?',
    job_stop: 'Detener trabajo',
    job_stop_confirm: '¿Está seguro de que desea detener este trabajo?',
    no_log_file: 'No hay archivo de registro disponible.',
    check_after_preprocessing: 'Verificar historial después de la ejecución',
    preprocessing_executed: 'Preprocesamiento ejecutado para ID:{dataId}',
    preprocessing_failed: 'El preprocesamiento falló',
    open_notebook: 'Abrir notebook',
    file_list: 'Lista de archivos',
    log_file_view: 'Ver archivo de registro',
    shell_launch: 'Iniciar Shell',
    tensorboard_show: 'Mostrar TensorBoard',
    checking_status: 'Verificando estado...',
    waiting_resource: 'Esperando recursos disponibles...',
    starting: 'Iniciando...',
    stopping: 'Deteniendo...',
    start_failed: 'Error al iniciar',
    git_not_selected:
      'No se ha seleccionado un repositorio Git. Contacte al administrador del sistema.',
    registry_not_selected:
      'No se ha seleccionado un Registry. Contacte al administrador del sistema.',
    token_display_warning:
      'El token solo se muestra al emitirlo. Asegúrese de guardarlo.',
    token_reissue_warning: 'Reemitir un token invalidará el token anterior.',
    token_issue: 'Emitir token',
    token_reissue: 'Reemitir',
    new_issue: 'Emitir nuevo',
    days_input_range: 'Ingrese un número entre 1 y 3650.',
    error_page_title: 'Se realizó una operación no válida.',
    error_page_not_found: 'No se encontró la página "{url}".',
    error_code: 'Código: {status}',
    error_message: 'Mensaje: {message}',
    error_resolution: 'Soluciones',
    error_retry: '- Intente la operación nuevamente',
    error_manual: '- Consulte el manual',
    error_server: 'Se ha registrado un error en el servidor.',
    error_patience:
      'Estamos trabajando arduamente para resolverlo. Por favor espere un momento.',
    data_too_large:
      'Los datos son demasiado grandes para mostrar. Descárguelos para verificar.',
    dataset_path_info:
      'Referencia: Rutas de datos y nombres para el dataset seleccionado [{name}]',
    no_available_nodes: 'No hay nodos disponibles.',
    contact_admin: 'Contacte al administrador del sistema.',
    resource_changed_from_original:
      'De los recursos solicitados originalmente, ',
    resource_value_changed: ' valores han sido cambiados.',
    node_no_resource:
      'El nodo no tiene suficientes recursos de {resources} para la solicitud.',
    no_executable_node:
      'Ningún nodo tiene suficientes recursos para ejecutar la solicitud.',
    latest_commit: 'Este es el commit más reciente.',
    commits_before: 'Esto está {index} commits antes del más reciente.',
    commits_older: 'Esto está más de {count} commits antes del más reciente.',
    committer_label: 'Autor del commit:',
    comment_none: 'Comentario: ninguno',
    comment_label: 'Comentario: ',
    training_delete_confirm:
      '¿Eliminar {count} historiales de entrenamiento? (El procesamiento puede tardar si hay muchos datos de salida)',
    training_deleted:
      'Historiales de entrenamiento eliminados. (Éxito: {success}, Fallidos: {fail})',
    inference_delete_confirm:
      '¿Eliminar {count} historiales de inferencia? (El procesamiento puede tardar si hay muchos datos de salida)',
    inference_deleted:
      'Historiales de inferencia eliminados. (Éxito: {success}, Fallidos: {fail})',
    only_completed_training:
      'La inferencia solo se puede ejecutar en entrenamientos con estado Completed o UserCanceled.',
    save_search_condition: 'Guardar condiciones de búsqueda',
    min_chars: 'Ingrese al menos {count} caracteres',
    shell_copy_paste:
      'Copiar: Ctrl+Insert, Pegar: Shift+Insert (En Google Chrome, Ctrl+Shift+V también funciona para pegar)',
    notebook_default_version: 'Predeterminado: 3.4.2',
    notebook_version_description:
      'Predeterminado: 3.4.2 (Se omitirá si JupyterLab ya está instalado en la imagen del contenedor)',
    tenant_user_remove_confirm:
      'Excluir al usuario le impedirá acceder al inquilino actual. Ingrese el nombre de usuario para continuar.',
  },

  // Cluster resource / Node view
  cluster: {
    by_node: 'Por nodo',
    by_tenant: 'Por inquilino',
    container_list: 'Lista de contenedores',
  },

  // LDAP
  ldap: {
    ldap_sync: 'Sincronización LDAP',
  },

  // Pagination
  pagination: {
    total: 'Total {total} elementos',
  },

  // Dashboard
  dashboard: {
    running_jobs: 'Trabajos en ejecución',
    favorite_jobs: 'Trabajos favoritos',
    no_running_jobs: 'No hay trabajos en ejecución',
    no_favorites: 'No hay favoritos',
  },

  // Search configs
  search: {
    name: 'Nombre',
    status: 'Estado',
  },

  // Steps
  steps: {
    training_name_dataset: 'Nombre de entrenamiento y dataset',
    inference_name_dataset: 'Nombre de inferencia y dataset',
    container_model: 'Contenedor y modelo',
    resource: 'Recurso',
    option: 'Opción',
    notebook_name: 'Nombre del notebook',
    resource_period: 'Recurso y período de inicio',
    optional: 'Opcional',
  },
}
