// es locale messages
const es = {
  common: {
    required: 'Este campo es obligatorio',
    yes: 'Sí',
    cancel: 'Cancelar',
    cancelled: 'Cancelado',
    confirm: 'Confirmar',
    register: 'Registrar',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    close: 'Cerrar',
    search: 'Buscar',
    error: 'Error',
    unlimited: 'Ilimitado',
    memory: 'Memoria',
    status: 'Estado',
    memo: 'Nota',
    tag: 'Etiqueta',
    name: 'Nombre',
    startDate: 'Fecha de inicio',
    endDate: 'Fecha de fin',
    createdDate: 'Fecha de registro',
    createdBy: 'Registrado por',
    executor: 'Ejecutor',
    command: 'Comando',
    dataset: 'Conjunto de datos',
    datasetName: 'Nombre del conjunto de datos',
    containerImage: 'Imagen de contenedor',
    model: 'Modelo',
    envVars: 'Variables de entorno',
    exposePorts: 'Puertos expuestos',
    waitTime: 'Tiempo de espera',
    execTime: 'Tiempo de ejecución',
    memoryGB: 'Memoria (GB)',
    partition: 'Partición',
    statusDetailLog: 'Registro detallado de estado',
    operation: 'Operación',
    stopJob: 'Detener trabajo',
    confirmStop: '¿Detener este trabajo?',
    outputFiles: 'Archivos de salida del contenedor',
    logFiles: 'Archivos de registro',
    fileList: 'Lista de archivos',
    datasetCreateMethod: 'Método de creación del conjunto de datos',
    symlink: 'Enlace simbólico',
    localCopy: 'Copia local',
    resultZip: 'Compresión Zip del resultado',
    noCompress: 'Sin compresión',
    compress: 'Comprimir',
    startupCommand: 'Comando de inicio',
    launchPeriodSetting: 'Configuración del período de ejecución',
    launchPeriodH: 'Período de ejecución (h)',
    launchPeriod: 'Período de ejecución',
    noLimit: 'Sin límite',
    local: 'Local',
    confirmDelete: '¿Eliminar este elemento?',
    noAvailableNodes: 'No hay nodos disponibles.',
    contactAdmin: 'Contacte al administrador del sistema.',
    originalResourceChanged1: 'El valor del recurso solicitado para ',
    originalResourceChanged2: ' ha sido modificado.',
    noResourceOnNode1: 'El nodo no tiene suficientes recursos de ',
    noResourceOnNode2: '.',
    noExecutableNode: 'Ningún nodo tiene suficientes recursos para ejecutar esta solicitud.',
    tagChange: 'Cambiar etiquetas',
    detailSearch: 'Búsqueda avanzada',
    searchInProgress: '(Búsqueda avanzada activa)',
    minChars4: 'Ingrese al menos 4 caracteres',
    saveSearchCondition: 'Guardar condiciones de búsqueda',
    registeredName: 'Nombre registrado',
    noLogFiles: 'No hay archivos de registro disponibles.',
    preprocessFailed: 'El preprocesamiento falló',
    dataRegistrationFailed: 'El registro de datos falló',
    inputMismatch: 'La entrada no coincide',
    fileSelectRequired: 'Seleccione al menos un archivo',
    brackLeft: '【',
    brackRight: '】',
    committer: 'Autor:',
    commentNone: 'Comentario: Ninguno)',
    comment: 'Comentario: ',
    starting: 'Iniciando',
    stopping: 'Deteniendo',
    remainingTime: 'Tiempo restante',
    pageGoTo: 'Ir a la página',
    allData: 'Todos los datos',
    removeSelection: 'Eliminar selección',
    displayName: 'Nombre para mostrar',
    only: 'Solo',
    after: 'Después',
    before: 'Antes',
    laterThan: 'Posterior a',
    earlierThan: 'Anterior a',
    equals: 'Igual a',
    greaterOrEqual: 'Mayor o igual',
    lessOrEqual: 'Menor o igual',
    greaterThan: 'Mayor que',
    exceeds: 'Excede',
    lessThan: 'Menor que',
    below: 'Por debajo',
    contains: 'Contiene',
    notContains: 'No contiene',
    test1: 'Prueba 1',
    detail1: 'Detalle 1',
    test2: 'Prueba 2',
    detail2: 'Detalle 2',
    test3: 'Prueba 3',
    detail3: 'Detalle 3',
    test4: 'Prueba 4',
    detail4: 'Detalle 4',
    mountedTraining: 'Entrenamiento montado',
    mountedTrainingDetail: 'Detalles del entrenamiento montado',
    mountedInference: 'Inferencia montada',
    mountedInferenceDetail: 'Detalles de la inferencia montada',
    datasetDetail: 'Detalles del conjunto de datos',
    preprocessing: 'Preprocesamiento',
    training: 'Entrenamiento',
    inference: 'Inferencia',
    notice: 'Aviso',
    completed: 'Completado',
    noPermission: 'Sin permiso',
    processedSuccessfully: 'Procesado exitosamente',
    execute: 'Ejecutar',
    newExecute: 'Nueva ejecución',
    newRegister: 'Nuevo registro',
    batchDelete: 'Eliminación masiva',
    batchAdd: 'Adición masiva',
    back: 'Volver',
    copyExecute: 'Copiar y ejecutar',
    stop: 'Detener',
    open: 'Abrir',
    start: 'Iniciar',
    restart: 'Reiniciar',
    forceStop: 'Detención forzada',
    normalStop: 'Detención normal',
    startShell: 'Iniciar Shell',
    add: 'Agregar',
    confirmStopJob: '¿Detener este trabajo?',
    containerAccess: 'Acceso al contenedor',
    batchDownloadCmd: 'Comando de descarga masiva',
    attachedFiles: 'Archivos adjuntos',
    viewLogFiles: 'Ver archivos de registro',
    checkingStatus: 'Verificando estado...',
    waitingForResources: 'Esperando recursos disponibles...',
    startingDots: 'Iniciando...',
    stoppingDots: 'Deteniendo...',
    startFailed: 'Error al iniciar',
    newTag: '+ Nueva etiqueta',
    nodeName: 'Nombre del nodo',
    nodeInfo: 'Información del nodo',
    requestedResource: 'Recursos solicitados',
    preprocessId: 'ID de preprocesamiento',
    dataTooLarge: 'Los datos son demasiado grandes para mostrar.',
    pleaseDownload: 'Descargue para revisar.',
    showImage: 'Mostrar imagen',
    tenantQuota: 'Cuota del inquilino',
    resourceLimit: 'Límite de recursos',
  },
  login: {
    title: 'Iniciar sesión',
    username: 'Nombre de usuario',
    password: 'Contraseña',
    loginButton: 'Iniciar sesión',
    authError: 'Error de autenticación: Inicie sesión.',
  },
  header: {
    userSettings: 'Configuración de usuario',
    logout: 'Cerrar sesión',
  },
  menu: {
    versionInfo: 'Información de versión',
  },
  dashboard: {
    title: 'Panel de control',
  },
  data: {
    title: 'Gestión de datos',
    dataName: 'Nombre de datos',
    dataRegister: 'Registrar datos',
    dataEdit: 'Editar datos',
    originalDataName: 'Nombre de datos original',
    dataFile: 'Archivo de datos',
  },
  dataset: {
    title: 'Gestión de conjuntos de datos',
    datasetName: 'Nombre del conjunto de datos',
    create: 'Crear conjunto de datos',
    edit: 'Editar conjunto de datos',
  },
  preprocessing: {
    title: 'Gestión de preprocesamiento',
    preprocessName: 'Nombre del preprocesamiento',
    preprocessHistory: 'Historial de preprocesamiento',
    preprocessRegister: 'Registrar preprocesamiento',
    preprocessEdit: 'Editar preprocesamiento',
    preprocessRun: 'Ejecutar preprocesamiento',
  },
  notebook: {
    title: 'Gestión de notebooks',
    notebookName: 'Nombre del notebook',
    notebookHistory: 'Historial de notebooks',
    notebookStart: 'Iniciar notebook',
    jupyterVersion: 'Versión de JupyterLab a instalar',
    jupyterDefault: 'Predeterminado: 3.4.2 (Se omite si JupyterLab ya está instalado en la imagen del contenedor)',
    jupyterDefaultShort: 'Predeterminado: 3.4.2',
    notebookNameAndResource: 'Nombre del notebook',
    resourceAndPeriod: 'Recurso y período de ejecución',
    optionalItems: 'Opcional',
    notebookUnlimitedExec: 'Ejecución ilimitada de notebook',
    prohibit: 'Prohibir',
    allow: 'Permitir',
  },
  training: {
    title: 'Gestión de entrenamiento',
    trainingName: 'Nombre del entrenamiento',
    trainingExec: 'Ejecutar entrenamiento',
    trainingHistory: 'Historial de entrenamiento',
    mountedTrainingId: 'ID de entrenamiento montado',
    mountedTrainingName: 'Nombre del entrenamiento montado',
    parentTrainingName: 'Nombre del entrenamiento padre',
    additionalResults: 'Resultados de entrenamiento adicionales a mostrar',
    additionalResultsShown: 'Resultados de entrenamiento adicionales mostrados',
    additionalResultsDetail: 'Detalles adicionales de entrenamiento mostrados',
    nameAndDataset: 'Nombre y conjunto de datos',
    containerAndModel: 'Contenedor y modelo',
    resource: 'Recurso',
    option: 'Opciones',
    onlyCompletedOrCanceled: 'Solo los entrenamientos con estado Completed o UserCanceled pueden ejecutar inferencia.',
    mountTraining: 'Montar entrenamiento',
  },
  inference: {
    title: 'Gestión de inferencia',
    inferenceName: 'Nombre de inferencia',
    create: 'Ejecutar inferencia',
    history: 'Historial de inferencia',
    mountedInferenceId: 'ID de inferencia montada',
    mountedInferenceName: 'Nombre de la inferencia montada',
    inferenceNotAvailable: 'La función de inferencia estará disponible en la versión del producto',
  },
  account: {
    title: 'Configuración de usuario',
    samePwdRequired: 'Ingrese la misma contraseña',
  },
  tenantSetting: {
    userTitle: 'Gestión de usuarios del inquilino',
    resourceTitle: 'Gestión de recursos del inquilino',
    settingTitle: 'Configuración del inquilino conectado',
    removeUserWarning: 'Al excluir un usuario, este no podrá acceder al inquilino actual. Ingrese el nombre de usuario para continuar.',
    authType: 'Tipo de autenticación',
    role: 'Rol',
  },
  systemSetting: {
    tenantTitle: 'Gestión de inquilinos',
    tenantRegister: 'Registrar inquilino',
    tenantEdit: 'Editar inquilino',
    tenantDeleteWarning: 'Al eliminar un inquilino, se perderán todos los datos asociados. Ingrese el nombre del inquilino para eliminar.',
    userGroupUnlinkWarning: 'Los usuarios de los grupos desvinculados no podrán unirse a este inquilino. ¿Guardar cambios?',
    gitTitle: 'Gestión de Git',
    gitRegister: 'Registrar Git',
    gitEdit: 'Editar Git',
    registryTitle: 'Gestión de registro',
    registryRegister: 'Registrar registro Docker',
    registryEdit: 'Editar registro Docker',
    storageTitle: 'Gestión de almacenamiento',
    storageRegister: 'Registrar almacenamiento',
    storageEdit: 'Editar almacenamiento',
    roleTitle: 'Gestión de roles',
    roleCreate: 'Crear rol',
    roleEdit: 'Editar rol',
    roleTenantCommon: 'Inquilino (Común)',
    roleSystem: 'Sistema',
    quotaTitle: 'Gestión de cuotas',
    userTitle: 'Gestión de usuarios',
    userRegister: 'Registrar usuario',
    userEdit: 'Editar usuario',
    ldapSync: 'Sincronización LDAP',
    ldapSyncTitle: 'Sincronización de usuarios LDAP',
    userGroupTitle: 'Gestión de grupos de usuarios',
    userGroupRegister: 'Registrar grupo de usuarios',
    userGroupEdit: 'Editar grupo de usuarios',
    nodeTitle: 'Gestión de nodos',
    nodeRegister: 'Registrar nodo',
    nodeEdit: 'Editar nodo',
    menuAccessTitle: 'Gestión de acceso al menú',
    resourceTitle: 'Uso de recursos',
    deleteAllContainerHistory: '¿Eliminar todo el historial de recursos de contenedores?',
    deleteAllJobHistory: '¿Eliminar todo el historial de ejecución de trabajos?',
    tenantId: 'ID del inquilino',
    tenantName: 'Nombre del inquilino',
  },
  version: {
    title: 'Información de versión',
    versionLabel: 'Versión:',
  },
  aquarium: {
    experiment: 'Experimento',
    experimentDetail: 'Detalles del experimento',
    experimentHistory: 'Historial de experimentos',
    experimentInfo: 'Información del experimento',
    experimentResult: 'Resultados del experimento',
    newTrainingExec: 'Ejecutar nuevo entrenamiento',
    templateName: 'Nombre de plantilla',
    modelTemplate: 'Plantilla de modelo',
    newTemplateRegister: 'Registrar nueva plantilla',
    templateRequiredFields: 'Los campos obligatorios no están completos: El nombre de la plantilla y la configuración de publicación son obligatorios.',
    noTemplatePermission: 'No tiene permiso para acceder a los detalles de la plantilla utilizada en este experimento',
    averagePrecision: 'Precisión promedio',
    dummyName: 'Demo Dummy 01',
    dataPreparation: 'Preparar datos',
    runExperiment: 'Ejecutar experimento',
    viewResults: 'Ver resultados',
    publishSetting: 'Configuración de publicación',
    public: 'Público',
    private: 'Privado',
    releaseNotes: 'Notas de la versión',
    entrypoint: 'Punto de entrada',
  },
}

export default es
