export default {
  // Common / Shared
  common: {
    required_field: '必須項目です',
    login: 'ログイン',
    logout: 'ログアウト',
    create: '作成',
    edit: '編集',
    delete: '削除',
    update: '更新',
    cancel: 'キャンセル',
    yes: 'はい',
    no: 'いいえ',
    save: '保存',
    close: '閉じる',
    copy: 'コピー',
    search: '検索',
    reload: 'リロード',
    execute: '実行',
    register: '登録',
    new_registration: '新規登録',
    new_creation: '新規作成',
    new_execution: '新規実行',
    batch_delete: '一括削除',
    batch_add: '一括追加',
    copy_execution: 'コピー実行',
    run_preprocessing: '前処理実行',
    detailed_search: '詳細検索',
    searching: '(詳細検索中)',
    version_info: 'バージョン情報',
    version_label: 'バージョン :',
    user_settings: 'ユーザ情報設定',
    data_download: 'データダウンロード',
    flat: 'フラット',
    with_header: 'あり',
    without_header: 'なし',
    group: 'グループ',
    system: 'システム',
    local: 'ローカル',
    default_label: '(デフォルト)',
    public_access: '公開',
    allow_logged_in: 'ログインユーザに許可',
    allowed: '許可',
    forbidden: '禁止',
    executable: '実行する',
    not_executable: '実行しない',
    editable: '可',
    not_editable: '不可',
    history: '履歴',
    script: 'スクリプト',
    tag_change: 'タグ変更',
    sync_start: '同期開始',
    start_date: '開始日',
    end_date: '終了日',
    count: '件数',
    count_suffix: '件',
    download_history: '履歴のダウンロード',
    delete_history: '履歴の削除',
    header_label: 'ヘッダー',
    saved_history: '保存されている履歴',
    confirm: '確定',
    cancelled: 'キャンセルされました',
    back: '戻る',
    view: '閲覧',
    get: '取得',
    open: '開く',
    start: '起動',
    stop: '停止',
    rerun: '再実行',
    restart: '再起動',
    test_notification: 'テスト通知',
    show_image: '画像を表示',
    new_tag: '+ 新規タグ',
    unlimited: '無制限',
    no_expiration: '無期限',
    default: 'デフォルト',
    contains: 'を含む',
    not_contains: 'を含まない',
    equals: 'と一致',
    gte: '以上',
    lte: '以下',
    gt: 'より上',
    lt: 'より下',
    gt_detail: '超過',
    lt_detail: '未満',
    local_copy: 'ローカルコピー',
    symbolic_link: 'シンボリックリンク',
    compress: '圧縮する',
    no_compress: '圧縮しない',
    normal_stop: '正常停止',
    abnormal_stop: '異常停止',
    inference_execution: '推論実行',
  },

  // Labels
  labels: {
    id: 'ID',
    name: '名前',
    memo: 'メモ',
    tag: 'タグ',
    tags: 'タグ',
    status: 'ステータス',
    type: '種別',
    created_at: '登録日時',
    created_at_short: '作成日時',
    started_at: '開始日時',
    execution_time_at: '実行日時',
    completed_at: '完了日時',
    created_by: '登録者',
    started_by: '実行者',
    author: '作成者',
    data_name: 'データ名',
    dataset_name: 'データセット名',
    training_name: '学習名',
    preprocessing_name: '前処理名',
    inference_name: '推論名',
    notebook_name: 'ノートブック名',
    entry_point: '実行コマンド',
    dataset: 'データセット',
    mounted_training: 'マウントした学習',
    mounted_inference: 'マウントした推論',
    parent_data_name: '元データ名',
    data_file: 'データファイル',
    placement_type: '配置種別',
    edit_permission: '編集可否',
    data: 'データ',
    registry_name: 'レジストリ名',
    registry_path: 'レジストリパス',
    gitlab_project: 'GitLabプロジェクト名',
    host_name: 'ホスト名',
    port: 'ポート',
    project_name: 'プロジェクト名',
    host_port: 'ホスト名:ポート',
    repository_name: 'リポジトリ名',
    repository_url: 'リポジトリURL',
    repository: 'リポジトリ',
    node_name: 'ノード名',
    node: 'ノード',
    tenant: 'テナント',
    tenant_name: 'テナント名',
    display_name: '表示名',
    partition: 'パーティション',
    access_level: 'アクセスレベル',
    access_denied: 'アクセス拒否',
    access_allowed: 'アクセス許可',
    access_permission_role: 'アクセス許可ロール',
    user_name: 'ユーザ名',
    user_display_name: 'ユーザ表示名',
    auth_type: '認証タイプ',
    password: 'パスワード',
    password_reenter: 'パスワード（再入力）',
    password_change_only: 'パスワード（変更する場合のみ入力）',
    system_role: 'システムロール',
    role: 'ロール',
    role_name: 'ロール名',
    sort_order: 'ソート順',
    display_order: '表示順',
    user_group_name: 'ユーザグループ名',
    tenant_role: 'テナントロール',
    storage_name: 'ストレージ名',
    access_key: 'アクセスキー',
    secret_key: 'シークレットキー',
    nfs_server: 'NFSサーバ',
    nfs_export_point: 'NFSエクスポートポイント',
    menu_name: 'メニュー名',
    description: '説明',
    container: 'コンテナ',
    container_name: 'コンテナ名',
    container_image: 'コンテナイメージ',
    memory: 'メモリ',
    memory_gb: 'メモリ(GB)',
    user: 'ユーザ',
    input_data_id: '入力データID',
    input_data_name: '入力データ名',
    dn_direct_users_only: 'DN直下のユーザのみ許可するか',
    notebook_unlimited_exec: 'ノートブック無期限実行',
    ldap_user_id: 'LDAPユーザID',
    ldap_password: 'LDAPパスワード',
    expiration: '有効期限',
    days: '日',
    git_repository: 'Gitリポジトリ',
    environment_variable: '環境変数',
    resource: 'リソース',
    cpu: 'cpu',
    gpu: 'gpu',
    option: 'オプション',
    zip_expand: 'zip展開',
    output_file: '出力ファイル',
    output_data_id: '出力データID',
    attached_file: '添付ファイル',
    result_file: '結果ファイル',
    execution_time: '実行時間',
    waiting_time: '待機時間',
    favorite: 'お気に入り',
    image_name: 'イメージ名',
    image: 'イメージ',
    token: 'トークン',
    default_tenant: 'デフォルトテナント',
    webhook_url: 'Webhook URL',
    expose_port: '開放ポート番号',
    expose_port_tcp: '開放ポート番号(TCP)',
    container_output_file: 'コンテナ出力ファイル',
    bulk_download_command: '一括ダウンロードコマンド',
    result_zip: '結果Zip圧縮',
    dataset_creation_method: 'データセット作成方式',
    model: 'モデル',
    startup_command: '起動時実行コマンド',
    startup_period: '起動期間',
    startup_period_h: '起動期間(h)',
    startup_period_setting: '起動期間設定',
    jupyter_version: 'インストールするJupyterLabのバージョン',
    operation: '操作',
    log: 'ログ',
    log_file: 'ログファイル',
    preprocessing_log: '前処理ログ',
    preprocessing_history_id: '前処理履歴ID',
    data_id: 'データID',
    storage_path: 'ストレージパス',
    storage_info: 'ストレージ情報',
    docker_registry_info: 'Dockerレジストリ情報',
    registry: 'レジストリ',
    git_info: 'Git情報',
    git_server: 'Gitサーバ',
    user_group_info: 'ユーザグループ情報',
    branch: 'ブランチ',
    commit_id: 'コミットID',
    committer: 'コミッター',
    commit_date: 'コミット日時',
    comment: 'コメント',
    file_name: 'ファイル名',
    size: 'サイズ',
    updated_at: '更新日時',
    variable_name: '変数名',
    value: '値',
    port_number: 'ポート番号',
    parent_training_name: '親学習名',
    mounted_training_id: 'マウントした学習ID',
    mounted_training_name: 'マウントした学習名',
    mounted_inference_id: 'マウントした推論ID',
    mounted_inference_name: 'マウントした推論名',
    output_value: '出力値',
    notification_url: '通知先URL',
    mention: 'メンション',
    current_password: '現在のパスワード(変更する場合のみ入力)',
    new_password: '新しいパスワード(変更する場合のみ入力)',
    reenter: '（再入力）',
    selected_git_repo: '選択中のGitリポジトリ',
    selected_registry: '選択中のRegistry',
    selected_tenant: '選択中のテナント',
    user_name_repo: 'ユーザ名/リポジトリ',
    remaining_time: '残り時間',
    additional_training_results: '追加表示した学習結果',
    container_access: 'コンテナアクセス',
    request_resource: '実行要求リソース',
    days_until_expiry: '期限切れまでの日数',
    registration_name: '登録名',
    quota_info: 'クォータ情報',
    default_tenant_label: '既定のテナント',
  },

  // Page Titles
  titles: {
    data_management: 'データ管理',
    dataset_management: 'データセット管理',
    training_management: '学習管理',
    inference_management: '推論管理',
    notebook_management: 'ノートブック管理',
    preprocessing_management: '前処理管理',
    preprocessing_history: '前処理履歴',
    registry_management: 'レジストリ管理',
    git_management: 'Git管理',
    storage_management: 'ストレージ管理',
    node_management: 'ノード管理',
    user_management: 'ユーザ管理',
    user_group_management: 'ユーザグループ管理',
    role_management: 'ロール管理',
    quota_management: 'クォータ管理',
    menu_access_management: 'メニューアクセス管理',
    resource_usage: 'リソース利用状況',
    tenant_management: 'テナント管理',
    data_registration: 'データ登録',
    data_edit: 'データ編集',
    dataset_creation: 'データセット作成',
    dataset_edit: 'データセット編集',
    training_creation: '学習作成',
    training_edit: '学習編集',
    training_history: '学習履歴',
    training_execution: '学習実行',
    inference_creation: '推論作成',
    inference_edit: '推論編集',
    inference_history: '推論履歴',
    inference_execution: '推論実行',
    notebook_creation: 'ノートブック作成',
    notebook_edit: 'ノートブック編集',
    notebook_history: 'ノートブック履歴',
    notebook_launch: 'ノートブック起動',
    preprocessing_creation: '前処理作成',
    preprocessing_edit: '前処理編集',
    preprocessing_history_edit: '前処理履歴編集',
    preprocessing_history_detail: '前処理履歴詳細',
    registry_registration: 'Dockerレジストリ登録',
    registry_edit: 'Dockerレジストリ編集',
    git_registration: 'Git登録',
    git_edit: 'Git編集',
    storage_registration: 'ストレージ登録',
    storage_edit: 'ストレージ編集',
    storage_info: 'ストレージ情報',
    registry_info: 'レジストリ情報',
    node_registration: 'ノード登録',
    node_edit: 'ノード編集',
    user_creation: 'ユーザ作成',
    user_edit: 'ユーザ編集',
    user_group_registration: 'ユーザグループ登録',
    user_group_edit: 'ユーザグループ編集',
    role_creation: 'ロール作成',
    role_edit: 'ロール編集',
    tenant_creation: 'テナント作成',
    tenant_edit: 'テナント編集',
    tenant_info: 'テナント情報',
    container_resource: 'コンテナリソース',
    job_execution_history: 'ジョブ実行履歴',
    ldap_sync: 'LDAPサーバ同期実行',
    dashboard: 'ダッシュボード',
    tenant_resource_management: 'テナントリソース管理',
    tenant_setting: '接続テナント設定',
    tenant_user_management: 'テナントユーザ管理',
    tenant_user_edit: 'テナントユーザ編集',
    user_info_settings: 'ユーザ情報設定',
    error: 'エラー',
    file_list: 'ファイル一覧',
    container_info: 'コンテナ情報',
    run_preprocessing: '前処理実行',
    container_execution_result: 'コンテナ実行結果',
    status_detail_log: 'ステータス詳細ログ',
    commit_detail: 'コミット詳細',
    mounted_training_detail: 'マウントした学習詳細',
    mounted_inference_detail: 'マウントした推論詳細',
    dataset_detail: 'データセット詳細',
    training_detail: '学習詳細',
    inference_detail: '推論詳細',
    preprocessing_detail: '前処理詳細',
    node_info: 'ノード情報',
    save_search: '検索条件の保存',
    add_training_results: '追加表示する学習結果',
  },

  // Messages
  messages: {
    process_success: '正常に処理されました',
    please_login: 'ログインしてください',
    no_valid_auth: '有効な認証情報がありません',
    auth_error: '認証エラー：ログインしてください。',
    select_one_file: 'ファイルを1つ以上選択してください',
    max_files: '1データの最大ファイル数は{max}です',
    data_registration_failed: 'データ登録に失敗しました',
    enter_same_password: '同一のパスワードを入力してください',
    role_not_selected: 'ロールが選択されていないテナントがあります',
    sort_order_description: '並び順。小さいほど前に表示される。一意性は不要。',
    tenant_delete_confirm:
      'テナントを削除すると、テナントに紐づくデータが失われます。処理を続けるにはテナント名を入力してください。',
    user_delete_confirm:
      'ユーザを削除すると、紐づいているテナントからユーザ情報が失われます。処理を続けるにはユーザ名を入力してください。',
    user_group_change_confirm:
      '紐づけが解除されたユーザグループに属するユーザはこのテナントに参加できなくなります。変更を保存しますか？',
    ldap_sync_description:
      'LDAPサーバに問い合わせを行い、全ユーザのテナント所属と権限情報の更新を行います。',
    ldap_sync_time_warning: '同期処理には時間がかかる場合があります。',
    ldap_sync_confirm:
      '同期処理を開始しますか？ユーザ数が多い場合、処理完了までに時間がかかる場合があります。',
    history_not_found: '履歴が見つかりませんでした。',
    auth_type_unknown: '認証タイプ：不明',
    user_group_tenants: 'ユーザグループ経由での所属しているテナント',
    user_group_tenant_roles: 'ユーザグループ経由でのテナントロール',
    delete_container_history_all: 'すべてのコンテナリソース履歴を削除しますか',
    delete_container_history_until: 'までのコンテナリソース履歴を削除しますか',
    delete_job_history_all: 'すべてのジョブ実行履歴を削除しますか',
    delete_job_history_until: 'までのジョブ実行履歴を削除しますか',
    move_to: '選択を {name} に移動',
    remove_selection: '選択を削除',
    page_of: 'ページ目へ',
    tenant_custom: 'テナント(カスタム)',
    tenant_common: 'テナント(共通)',
    tenant_custom_with_name: 'テナント(カスタム) / ',
    input_mismatch: '入力内容が不一致です',
    delete_confirm: '削除しますか',
    delete_confirm_output:
      '削除しますか（出力データ数が多い場合、処理に時間がかかります）',
    stop_confirm: '停止しますか',
    job_stop: 'ジョブ停止',
    job_stop_confirm: 'ジョブを停止しますか',
    no_log_file: '取得可能なログファイルはありません。',
    check_after_preprocessing: '実行後に履歴を確認する',
    preprocessing_executed: 'ID:{dataId}の前処理を実行しました',
    preprocessing_failed: '前処理に失敗しました',
    open_notebook: 'ノートブックを開く',
    file_list: 'ファイル一覧',
    log_file_view: 'ログファイル閲覧',
    shell_launch: 'Shell起動',
    tensorboard_show: 'TensorBoard表示',
    checking_status: '状態確認中...',
    waiting_resource: '利用可能リソース待機中...',
    starting: '起動中...',
    stopping: '停止中...',
    start_failed: '起動失敗',
    git_not_selected:
      'Gitリポジトリが選択されていません。 システム管理者にお問い合わせください。',
    registry_not_selected:
      'Registryが選択されていません。 システム管理者にお問い合わせください。',
    token_display_warning:
      'トークンは発行時のみ表示されます。必ず保存してください。',
    token_reissue_warning:
      'トークンを再発行すると、以前のトークンは使用できなくなります。',
    token_issue: 'トークン発行',
    token_reissue: '再発行',
    new_issue: '新規発行',
    days_input_range: '値は 1 ～ 3650 の数字を入力して下さい。',
    error_page_title: '不正な操作が行われました。',
    error_page_not_found: '"{url}" のページが見つかりませんでした。',
    error_code: 'コード：{status}',
    error_message: 'メッセージ：{message}',
    error_resolution: '解決方法',
    error_retry: '・再度操作を行ってください',
    error_manual: '・マニュアルを確認',
    error_server: 'サーバにエラーが記録されました。',
    error_patience: '現在、鋭意努力しておりますので今しばらくお待ちください。',
    data_too_large:
      'データが大きすぎるため表示できません。ダウンロードして確認してください。',
    dataset_path_info:
      '参考：選択したデータセット【{name}】のデータパス、データ名一覧',
    no_available_nodes: '利用可能なノードがありません。',
    contact_admin: 'システム管理者に確認してください。',
    resource_changed_from_original: '元々の要求リソースから',
    resource_value_changed: 'の値が変更されています。',
    node_no_resource: 'ノードに要求分の{resources}のリソースがありません。',
    no_executable_node: '要求分のリソースで実行可能なノードがありません。',
    latest_commit: '最新のコミットです。',
    commits_before: '最新から{index}コミット前のIDです。',
    commits_older: '最新から{count}コミットより前のIDです。',
    committer_label: 'コミッター:',
    comment_none: 'コメント: なし',
    comment_label: 'コメント: ',
    training_delete_confirm:
      '学習履歴を{count}件削除しますか（出力データ数が多い場合、処理に時間がかかります）',
    training_deleted:
      '学習履歴を削除しました。(成功：{success}件、 失敗：{fail}件',
    inference_delete_confirm:
      '推論履歴を{count}件削除しますか（出力データ数が多い場合、処理に時間がかかります）',
    inference_deleted:
      '推論履歴を削除しました。(成功：{success}件、 失敗：{fail}件）',
    only_completed_training:
      'ステータスがCompletedまたはUserCanceledの学習のみ推論を実行できます。',
    save_search_condition: '検索条件を保存',
    min_chars: '{count}文字以上で入力してください',
    shell_copy_paste:
      'コピー: Ctrl+Insert, ペースト: Shift+Insert(Google Chromeの場合Ctrl+Shift+Vでペーストも可能)',
    notebook_default_version: 'デフォルト: 3.4.2',
    notebook_version_description:
      'デフォルト: 3.4.2 (JupyterLabがインストール済みのコンテナイメージでは選択してもスキップされます)',
    tenant_user_remove_confirm:
      'ユーザを除外すると、対象ユーザは現在のテナントに入れなくなります。処理を続けるにはユーザ名を入力してください。',
  },

  // Cluster resource / Node view
  cluster: {
    by_node: 'ノード別',
    by_tenant: 'テナント別',
    container_list: 'コンテナ一覧',
  },

  // LDAP
  ldap: {
    ldap_sync: 'LDAP同期',
  },

  // Pagination
  pagination: {
    total: '合計 {total} 件',
  },

  // Dashboard
  dashboard: {
    running_jobs: '実行中のジョブ',
    favorite_jobs: 'お気に入りジョブ',
    no_running_jobs: '実行中のジョブはありません',
    no_favorites: 'お気に入りはありません',
  },

  // Search configs
  search: {
    name: '名前',
    status: 'ステータス',
  },

  // Steps
  steps: {
    training_name_dataset: '学習名 & データセット',
    inference_name_dataset: '推論名 & データセット',
    container_model: 'コンテナ & モデル',
    resource: 'リソース',
    option: 'オプション',
    notebook_name: 'ノートブック名',
    resource_period: 'リソース & 起動期間',
    optional: '任意項目',
  },
}
