// ja locale messages
const ja = {
  common: {
    required: '必須項目です',
    yes: 'はい',
    cancel: 'キャンセル',
    cancelled: 'キャンセルされました',
    confirm: '確定',
    register: '登録',
    edit: '編集',
    delete: '削除',
    save: '保存',
    close: '閉じる',
    search: '検索',
    error: 'エラー',
    unlimited: '無制限',
    memory: 'メモリ',
    status: 'ステータス',
    memo: 'メモ',
    tag: 'タグ',
    name: '名前',
    startDate: '開始日時',
    endDate: '完了日時',
    createdDate: '登録日時',
    createdBy: '登録者',
    executor: '実行者',
    command: '実行コマンド',
    dataset: 'データセット',
    datasetName: 'データセット名',
    containerImage: 'コンテナイメージ',
    model: 'モデル',
    envVars: '環境変数',
    exposePorts: '開放ポート番号',
    waitTime: '待機時間',
    execTime: '実行時間',
    memoryGB: 'メモリ(GB)',
    partition: 'パーティション',
    statusDetailLog: 'ステータス詳細ログ',
    operation: '操作',
    stopJob: 'ジョブ停止',
    confirmStop: '停止しますか',
    outputFiles: 'コンテナ出力ファイル',
    logFiles: 'ログファイル',
    fileList: 'ファイル一覧',
    datasetCreateMethod: 'データセット作成方式',
    symlink: 'シンボリックリンク',
    localCopy: 'ローカルコピー',
    resultZip: '結果Zip圧縮',
    noCompress: '圧縮しない',
    compress: '圧縮する',
    startupCommand: '起動時実行コマンド',
    launchPeriodSetting: '起動期間設定',
    launchPeriodH: '起動期間(h)',
    launchPeriod: '起動期間',
    noLimit: '無期限',
    local: 'ローカル',
    confirmDelete: '削除しますか',
    noAvailableNodes: '利用可能なノードがありません。',
    contactAdmin: 'システム管理者に確認してください。',
    originalResourceChanged1: '元々の要求リソースから',
    originalResourceChanged2: 'の値が変更されています。',
    noResourceOnNode1: 'ノードに要求分の',
    noResourceOnNode2: 'のリソースがありません。',
    noExecutableNode: '要求分のリソースで実行可能なノードがありません。',
    tagChange: 'タグ変更',
    detailSearch: '詳細検索',
    searchInProgress: '(詳細検索中)',
    minChars4: '4文字以上で入力してください',
    saveSearchCondition: '検索条件の保存',
    registeredName: '登録名',
    noLogFiles: '取得可能なログファイルはありません。',
    preprocessFailed: '前処理に失敗しました',
    dataRegistrationFailed: 'データ登録に失敗しました',
    inputMismatch: '入力内容が不一致です',
    fileSelectRequired: 'ファイルを1つ以上選択してください',
    brackLeft: '【',
    brackRight: '】',
    committer: 'コミッター:',
    commentNone: 'コメント: なし)',
    comment: 'コメント: ',
    starting: '起動中',
    stopping: '停止中',
    remainingTime: '残り時間',
    pageGoTo: 'ページ目へ',
    allData: 'all　data',
    removeSelection: '選択を削除',
    displayName: '表示名',
    only: 'のみ',
    after: '以降',
    before: '以前',
    laterThan: 'より後',
    earlierThan: 'より前',
    equals: 'と一致',
    greaterOrEqual: '以上',
    lessOrEqual: '以下',
    greaterThan: 'より上',
    exceeds: '超過',
    lessThan: 'より下',
    below: '未満',
    contains: 'を含む',
    notContains: 'を含まない',
    test1: 'テスト1',
    detail1: '詳細１',
    test2: 'テスト2',
    detail2: '詳細２',
    test3: 'テスト3',
    detail3: '詳細３',
    test4: 'テスト4',
    detail4: '詳細４',
    mountedTraining: 'マウントした学習',
    mountedTrainingDetail: 'マウントした学習詳細',
    mountedInference: 'マウントした推論',
    mountedInferenceDetail: 'マウントした推論詳細',
    datasetDetail: 'データセット詳細',
    preprocessing: '前処理',
    training: '学習',
    inference: '推論',
    notice: 'お知らせ',
    completed: '完了',
    noPermission: '権限がありません',
    execute: '実行',
    newExecute: '新規実行',
    newRegister: '新規登録',
    batchDelete: '一括削除',
    batchAdd: '一括追加',
    back: '戻る',
    copyExecute: 'コピー実行',
    stop: '停止',
    open: '開く',
    start: '起動',
    restart: '再起動',
    forceStop: '異常停止',
    normalStop: '正常停止',
    startShell: 'Shell起動',
    add: '追加',
    confirmStopJob: 'ジョブを停止しますか',
    containerAccess: 'コンテナアクセス',
    batchDownloadCmd: '一括ダウンロードコマンド',
    attachedFiles: '添付ファイル',
    viewLogFiles: 'ログファイル閲覧',
    checkingStatus: '状態確認中...',
    waitingForResources: '利用可能リソース待機中...',
    startingDots: '起動中...',
    stoppingDots: '停止中...',
    startFailed: '起動失敗',
    newTag: '＋ 新規タグ',
    nodeName: 'ノード名',
    nodeInfo: 'ノード情報',
    requestedResource: '実行要求リソース',
    preprocessId: '前処理ID',
    dataTooLarge: 'データが大きすぎるため表示できません。',
    pleaseDownload: 'ダウンロードして確認してください。',
    showImage: '画像を表示',
    tenantQuota: 'テナントクォータ',
    resourceLimit: 'リソース制限',
  },
  login: {
    title: 'ログイン',
    username: 'ユーザ名',
    password: 'パスワード',
    loginButton: 'ログイン',
    authError: '認証エラー：ログインしてください。',
  },
  header: {
    userSettings: 'ユーザ情報設定',
    logout: 'ログアウト',
  },
  menu: {
    versionInfo: 'バージョン情報',
  },
  dashboard: {
    title: 'ダッシュボード',
  },
  data: {
    title: 'データ管理',
    dataName: 'データ名',
    dataRegister: 'データ登録',
    dataEdit: 'データ編集',
    originalDataName: '元データ名',
    dataFile: 'データファイル',
  },
  dataset: {
    title: 'データセット管理',
    datasetName: 'データセット名',
    create: 'データセット作成',
    edit: 'データセット編集',
  },
  preprocessing: {
    title: '前処理管理',
    preprocessName: '前処理名',
    preprocessHistory: '前処理履歴',
    preprocessRegister: '前処理登録',
    preprocessEdit: '前処理編集',
    preprocessRun: '前処理実行',
  },
  notebook: {
    title: 'ノートブック管理',
    notebookName: 'ノートブック名',
    notebookHistory: 'ノートブック履歴',
    notebookStart: 'ノートブック起動',
    jupyterVersion: 'インストールするJupyterLabのバージョン',
    jupyterDefault: 'デフォルト: 3.4.2 (JupyterLabがインストール済みのコンテナイメージでは選択してもスキップされます)',
    jupyterDefaultShort: 'デフォルト: 3.4.2',
    notebookNameAndResource: 'ノートブック名',
    resourceAndPeriod: 'リソース & 起動期間',
    optionalItems: '任意項目',
    notebookUnlimitedExec: 'ノートブック無期限実行',
    prohibit: '禁止',
    allow: '許可',
  },
  training: {
    title: '学習管理',
    trainingName: '学習名',
    trainingExec: '学習実行',
    trainingHistory: '学習履歴',
    mountedTrainingId: 'マウントした学習ID',
    mountedTrainingName: 'マウントした学習名',
    parentTrainingName: '親学習名',
    additionalResults: '追加表示する学習結果',
    additionalResultsShown: '追加表示した学習結果',
    additionalResultsDetail: '追加表示した学習詳細',
    nameAndDataset: '学習名 & データセット',
    containerAndModel: 'コンテナ & モデル',
    resource: 'リソース',
    option: 'オプション',
    onlyCompletedOrCanceled: 'ステータスがCompletedまたはUserCanceledの学習のみ推論を実行できます。',
    mountTraining: 'マウントする学習',
  },
  inference: {
    title: '推論管理',
    inferenceName: '推論名',
    create: '推論実行',
    history: '推論履歴',
    mountedInferenceId: 'マウントした推論ID',
    mountedInferenceName: 'マウントした推論名',
    inferenceNotAvailable: '推論機能は製品版で使用可能予定です',
  },
  account: {
    title: 'ユーザ情報設定',
    samePwdRequired: '同一のパスワードを入力してください',
  },
  tenantSetting: {
    userTitle: 'テナントユーザ管理',
    resourceTitle: 'テナントリソース管理',
    settingTitle: '接続テナント設定',
    removeUserWarning: 'ユーザを除外すると、対象ユーザは現在のテナントに入れなくなります。処理を続けるにはユーザ名を入力してください。',
    authType: '認証タイプ',
    role: 'ロール',
  },
  systemSetting: {
    tenantTitle: 'テナント管理',
    tenantRegister: 'テナント登録',
    tenantEdit: 'テナント編集',
    tenantDeleteWarning: 'テナントを削除すると、テナントに紐づくデータが失われます。テナントを削除するにはテナント名を入力してください。',
    userGroupUnlinkWarning: '紐づけが解除されたユーザグループに属するユーザはこのテナントに参加できなくなります。変更を保存しますか？',
    gitTitle: 'Git管理',
    gitRegister: 'Git登録',
    gitEdit: 'Git編集',
    registryTitle: 'レジストリ管理',
    registryRegister: 'Dockerレジストリ登録',
    registryEdit: 'Dockerレジストリ編集',
    storageTitle: 'ストレージ管理',
    storageRegister: 'ストレージ登録',
    storageEdit: 'ストレージ編集',
    roleTitle: 'ロール管理',
    roleCreate: 'ロール作成',
    roleEdit: 'ロール編集',
    roleTenantCommon: 'テナント(共通)',
    roleSystem: 'システム',
    quotaTitle: 'クォータ管理',
    userTitle: 'ユーザ管理',
    userRegister: 'ユーザ登録',
    userEdit: 'ユーザ編集',
    ldapSync: 'LDAP同期',
    ldapSyncTitle: 'LDAPユーザ同期',
    userGroupTitle: 'ユーザグループ管理',
    userGroupRegister: 'ユーザグループ登録',
    userGroupEdit: 'ユーザグループ編集',
    nodeTitle: 'ノード管理',
    nodeRegister: 'ノード登録',
    nodeEdit: 'ノード編集',
    menuAccessTitle: 'メニューアクセス管理',
    resourceTitle: 'リソース利用状況',
    deleteAllContainerHistory: 'すべてのコンテナリソース履歴を削除しますか',
    deleteAllJobHistory: 'すべてのジョブ実行履歴を削除しますか',
    tenantId: 'テナントID',
    tenantName: 'テナント名',
  },
  version: {
    title: 'バージョン情報',
    versionLabel: 'バージョン :',
  },
  aquarium: {
    experiment: '実験',
    experimentDetail: '実験詳細',
    experimentHistory: '実験履歴',
    experimentInfo: '実験情報',
    experimentResult: '実験結果',
    newTrainingExec: '新規学習実行',
    templateName: 'テンプレート名',
    modelTemplate: 'モデルテンプレート',
    newTemplateRegister: '新しいテンプレートの登録',
    templateRequiredFields: '必須項目が入力されていません : テンプレート名、公開設定は必須項目です。',
    noTemplatePermission: 'この実験に使用されたテンプレートの詳細にアクセスする権限がありません',
    averagePrecision: '平均適合率',
    dummyName: '体験版用ダミー01',
    dataPreparation: 'データの準備を行う',
    runExperiment: '実験を行う',
    viewResults: '実験結果を確認する',
    publishSetting: '公開設定',
    public: '公開',
    private: '非公開',
    releaseNotes: 'リリースノート',
    entrypoint: 'エントリポイント',
  },
}

export default ja
