// en locale messages
const en = {
  common: {
    required: 'This field is required',
    yes: 'Yes',
    cancel: 'Cancel',
    cancelled: 'Cancelled',
    confirm: 'Confirm',
    register: 'Register',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    close: 'Close',
    search: 'Search',
    error: 'Error',
    unlimited: 'Unlimited',
    memory: 'Memory',
    status: 'Status',
    memo: 'Memo',
    tag: 'Tag',
    name: 'Name',
    startDate: 'Start Date',
    endDate: 'End Date',
    createdDate: 'Created Date',
    createdBy: 'Created By',
    executor: 'Executor',
    command: 'Command',
    dataset: 'Dataset',
    datasetName: 'Dataset Name',
    containerImage: 'Container Image',
    model: 'Model',
    envVars: 'Environment Variables',
    exposePorts: 'Exposed Ports',
    waitTime: 'Wait Time',
    execTime: 'Execution Time',
    memoryGB: 'Memory (GB)',
    partition: 'Partition',
    statusDetailLog: 'Status Detail Log',
    operation: 'Operation',
    stopJob: 'Stop Job',
    confirmStop: 'Stop this job?',
    outputFiles: 'Container Output Files',
    logFiles: 'Log Files',
    fileList: 'File List',
    datasetCreateMethod: 'Dataset Creation Method',
    symlink: 'Symbolic Link',
    localCopy: 'Local Copy',
    resultZip: 'Result Zip Compression',
    noCompress: 'No Compression',
    compress: 'Compress',
    startupCommand: 'Startup Command',
    launchPeriodSetting: 'Launch Period Setting',
    launchPeriodH: 'Launch Period (h)',
    launchPeriod: 'Launch Period',
    noLimit: 'Unlimited',
    local: 'Local',
    confirmDelete: 'Delete this item?',
    noAvailableNodes: 'No available nodes.',
    contactAdmin: 'Please contact the system administrator.',
    originalResourceChanged1: 'The requested resource value for ',
    originalResourceChanged2: ' has been changed.',
    noResourceOnNode1: 'The node does not have enough ',
    noResourceOnNode2: ' resources.',
    noExecutableNode: 'No node has enough resources to execute this request.',
    tagChange: 'Change Tags',
    detailSearch: 'Advanced Search',
    searchInProgress: '(Advanced search active)',
    minChars4: 'Please enter at least 4 characters',
    saveSearchCondition: 'Save Search Conditions',
    registeredName: 'Registered Name',
    noLogFiles: 'No log files available.',
    preprocessFailed: 'Preprocessing failed',
    dataRegistrationFailed: 'Data registration failed',
    inputMismatch: 'Input does not match',
    fileSelectRequired: 'Please select at least one file',
    brackLeft: '【',
    brackRight: '】',
    committer: 'Committer:',
    commentNone: 'Comment: None)',
    comment: 'Comment: ',
    starting: 'Starting',
    stopping: 'Stopping',
    remainingTime: 'Remaining Time',
    pageGoTo: 'Go to page',
    allData: 'All Data',
    removeSelection: 'Remove Selection',
    displayName: 'Display Name',
    only: 'Only',
    after: 'After',
    before: 'Before',
    laterThan: 'Later than',
    earlierThan: 'Earlier than',
    equals: 'Equals',
    greaterOrEqual: 'Greater or equal',
    lessOrEqual: 'Less or equal',
    greaterThan: 'Greater than',
    exceeds: 'Exceeds',
    lessThan: 'Less than',
    below: 'Below',
    contains: 'Contains',
    notContains: 'Does not contain',
    test1: 'Test 1',
    detail1: 'Detail 1',
    test2: 'Test 2',
    detail2: 'Detail 2',
    test3: 'Test 3',
    detail3: 'Detail 3',
    test4: 'Test 4',
    detail4: 'Detail 4',
    mountedTraining: 'Mounted Training',
    mountedTrainingDetail: 'Mounted Training Details',
    mountedInference: 'Mounted Inference',
    mountedInferenceDetail: 'Mounted Inference Details',
    datasetDetail: 'Dataset Details',
    preprocessing: 'Preprocessing',
    training: 'Training',
    inference: 'Inference',
    notice: 'Notice',
    completed: 'Completed',
    noPermission: 'No permission',
    processedSuccessfully: 'Processed successfully',
    execute: 'Execute',
    newExecute: 'New Execution',
    newRegister: 'New Registration',
    batchDelete: 'Batch Delete',
    batchAdd: 'Batch Add',
    back: 'Back',
    copyExecute: 'Copy & Execute',
    stop: 'Stop',
    open: 'Open',
    start: 'Start',
    restart: 'Restart',
    forceStop: 'Force Stop',
    normalStop: 'Normal Stop',
    startShell: 'Start Shell',
    add: 'Add',
    confirmStopJob: 'Stop this job?',
    containerAccess: 'Container Access',
    batchDownloadCmd: 'Batch Download Command',
    attachedFiles: 'Attached Files',
    viewLogFiles: 'View Log Files',
    checkingStatus: 'Checking status...',
    waitingForResources: 'Waiting for available resources...',
    startingDots: 'Starting...',
    stoppingDots: 'Stopping...',
    startFailed: 'Start Failed',
    newTag: '+ New Tag',
    nodeName: 'Node Name',
    nodeInfo: 'Node Info',
    requestedResource: 'Requested Resources',
    preprocessId: 'Preprocess ID',
    dataTooLarge: 'Data is too large to display.',
    pleaseDownload: 'Please download to review.',
    showImage: 'Show Image',
    tenantQuota: 'Tenant Quota',
    resourceLimit: 'Resource Limit',
  },
  login: {
    title: 'Login',
    username: 'Username',
    password: 'Password',
    loginButton: 'Login',
    authError: 'Authentication error: Please log in.',
  },
  header: {
    userSettings: 'User Settings',
    logout: 'Logout',
  },
  menu: {
    versionInfo: 'Version Info',
  },
  dashboard: {
    title: 'Dashboard',
  },
  data: {
    title: 'Data Management',
    dataName: 'Data Name',
    dataRegister: 'Register Data',
    dataEdit: 'Edit Data',
    originalDataName: 'Original Data Name',
    dataFile: 'Data File',
  },
  dataset: {
    title: 'Dataset Management',
    datasetName: 'Dataset Name',
    create: 'Create Dataset',
    edit: 'Edit Dataset',
  },
  preprocessing: {
    title: 'Preprocessing Management',
    preprocessName: 'Preprocess Name',
    preprocessHistory: 'Preprocess History',
    preprocessRegister: 'Register Preprocess',
    preprocessEdit: 'Edit Preprocess',
    preprocessRun: 'Run Preprocess',
  },
  notebook: {
    title: 'Notebook Management',
    notebookName: 'Notebook Name',
    notebookHistory: 'Notebook History',
    notebookStart: 'Start Notebook',
    jupyterVersion: 'JupyterLab Version to Install',
    jupyterDefault: 'Default: 3.4.2 (Skipped if JupyterLab is already installed in the container image)',
    jupyterDefaultShort: 'Default: 3.4.2',
    notebookNameAndResource: 'Notebook Name',
    resourceAndPeriod: 'Resource & Launch Period',
    optionalItems: 'Optional',
    notebookUnlimitedExec: 'Unlimited Notebook Execution',
    prohibit: 'Prohibit',
    allow: 'Allow',
  },
  training: {
    title: 'Training Management',
    trainingName: 'Training Name',
    trainingExec: 'Run Training',
    trainingHistory: 'Training History',
    mountedTrainingId: 'Mounted Training ID',
    mountedTrainingName: 'Mounted Training Name',
    parentTrainingName: 'Parent Training Name',
    additionalResults: 'Additional Training Results to Display',
    additionalResultsShown: 'Additional Training Results Shown',
    additionalResultsDetail: 'Additional Training Details Shown',
    nameAndDataset: 'Name & Dataset',
    containerAndModel: 'Container & Model',
    resource: 'Resource',
    option: 'Options',
    onlyCompletedOrCanceled: 'Only training with Completed or UserCanceled status can run inference.',
    mountTraining: 'Mount Training',
  },
  inference: {
    title: 'Inference Management',
    inferenceName: 'Inference Name',
    create: 'Run Inference',
    history: 'Inference History',
    mountedInferenceId: 'Mounted Inference ID',
    mountedInferenceName: 'Mounted Inference Name',
    inferenceNotAvailable: 'Inference function will be available in the product version',
  },
  account: {
    title: 'User Settings',
    samePwdRequired: 'Please enter the same password',
  },
  tenantSetting: {
    userTitle: 'Tenant User Management',
    resourceTitle: 'Tenant Resource Management',
    settingTitle: 'Connected Tenant Settings',
    removeUserWarning: 'Removing a user will prevent them from accessing the current tenant. Please enter the username to proceed.',
    authType: 'Auth Type',
    role: 'Role',
  },
  systemSetting: {
    tenantTitle: 'Tenant Management',
    tenantRegister: 'Register Tenant',
    tenantEdit: 'Edit Tenant',
    tenantDeleteWarning: 'Deleting a tenant will result in loss of all associated data. Please enter the tenant name to delete.',
    userGroupUnlinkWarning: 'Users belonging to unlinked user groups will no longer be able to join this tenant. Save changes?',
    gitTitle: 'Git Management',
    gitRegister: 'Register Git',
    gitEdit: 'Edit Git',
    registryTitle: 'Registry Management',
    registryRegister: 'Register Docker Registry',
    registryEdit: 'Edit Docker Registry',
    storageTitle: 'Storage Management',
    storageRegister: 'Register Storage',
    storageEdit: 'Edit Storage',
    roleTitle: 'Role Management',
    roleCreate: 'Create Role',
    roleEdit: 'Edit Role',
    roleTenantCommon: 'Tenant (Common)',
    roleSystem: 'System',
    quotaTitle: 'Quota Management',
    userTitle: 'User Management',
    userRegister: 'Register User',
    userEdit: 'Edit User',
    ldapSync: 'LDAP Sync',
    ldapSyncTitle: 'LDAP User Sync',
    userGroupTitle: 'User Group Management',
    userGroupRegister: 'Register User Group',
    userGroupEdit: 'Edit User Group',
    nodeTitle: 'Node Management',
    nodeRegister: 'Register Node',
    nodeEdit: 'Edit Node',
    menuAccessTitle: 'Menu Access Management',
    resourceTitle: 'Resource Usage',
    deleteAllContainerHistory: 'Delete all container resource history?',
    deleteAllJobHistory: 'Delete all job execution history?',
    tenantId: 'Tenant ID',
    tenantName: 'Tenant Name',
  },
  version: {
    title: 'Version Info',
    versionLabel: 'Version:',
  },
  aquarium: {
    experiment: 'Experiment',
    experimentDetail: 'Experiment Details',
    experimentHistory: 'Experiment History',
    experimentInfo: 'Experiment Info',
    experimentResult: 'Experiment Results',
    newTrainingExec: 'Run New Training',
    templateName: 'Template Name',
    modelTemplate: 'Model Template',
    newTemplateRegister: 'Register New Template',
    templateRequiredFields: 'Required fields are not filled: Template name and publish settings are required.',
    noTemplatePermission: 'You do not have permission to access the template details used in this experiment',
    averagePrecision: 'Average Precision',
    dummyName: 'Demo Dummy 01',
    dataPreparation: 'Prepare Data',
    runExperiment: 'Run Experiment',
    viewResults: 'View Results',
    publishSetting: 'Publish Setting',
    public: 'Public',
    private: 'Private',
    releaseNotes: 'Release Notes',
    entrypoint: 'Entry Point',
  },
}

export default en
